# Generated by Django 5.1.5 on 2025-01-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(max_length=1024, verbose_name="Сообщение"),
                ),
                ("recipient", models.JSONField(verbose_name="Получатели")),
                (
                    "delay",
                    models.IntegerField(
                        choices=[
                            (0, "Отправить без задержки"),
                            (1, "Отправить с задержной 1 час"),
                            (2, "Отправить с задержной 2 часа"),
                        ],
                        verbose_name="Задержка отправки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="NotifyAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(verbose_name="Дата и время попытки отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failure", "Не успешно")],
                        max_length=7,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("mail", "Почта"), ("telegram", "Телеграм")],
                        max_length=8,
                        verbose_name="Сервис",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
                ),
                (
                    "notify",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="notifications.notify",
                        verbose_name="Уведомление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка уведомления",
                "verbose_name_plural": "Попытки уведомления",
                "ordering": ["id"],
            },
        ),
    ]
